import Link from "next/link";
import { ArrowRight, Check, Code2, FileCheck2, LockKeyhole, ScanSearch, ShieldCheck, Sparkles } from "lucide-react";

import { KavachSiteShell } from "@/components/kavach-site-shell";
import styles from "@/components/kavach-story-pages.module.css";

const nodes = [
  { number: "01", label: "DISCOVER", title: "Bounded input", copy: "Declared OpenAPI surface, synthetic identities, request ceilings, and egress denial.", icon: ScanSearch },
  { number: "02", label: "REASON", title: "Structured advice", copy: "Source and runtime evidence become a constrained vulnerability hypothesis and patch plan.", icon: Sparkles },
  { number: "03", label: "PATCH", title: "Isolated change", copy: "Approved transformations land in an ephemeral worktree with a recorded diff and hash.", icon: Code2 },
  { number: "04", label: "PROVE", title: "Verifier gate", copy: "Exploit replay must fail while authorised behaviour and regression tests remain green.", icon: FileCheck2 },
];

export default function ArchitecturePage() {
  return <KavachSiteShell chapter="03 / THE SYSTEM MAP"><div className={styles.page}><section className={styles.section}><div className={styles.sectionHead}><div><span className={styles.sectionTag}>ARCHITECTURE / BOUNDED AUTONOMY</span><div className={styles.heroMeta}><i /> THE MODEL NEVER OWNS THE LAST WORD</div></div><div><h1 className={styles.sectionTitle}>Autonomy is a<br /><em>contract.</em></h1><p className={styles.sectionLead}>Every hand-off is explicit. The model can propose a change, but policy decides whether it may be applied and the verifier decides whether it survives.</p></div></div><div className={styles.architectureCanvas}><div className={styles.architectureLine} /><div className={styles.architectureNodes}>{nodes.map(({ number, label, title, copy, icon: Icon }) => <article className={styles.architectureNode} key={number}><div className={styles.architectureNodeNumber}><span>{number}</span><Icon size={16} /></div><h2>{title}</h2><p>{copy}</p><span className={styles.caseLabel}>{label}</span></article>)}</div><div className={styles.architectureNote}><span>NO EXTERNAL EGRESS</span><span>NO ARBITRARY TOOL EXECUTION</span><span>HUMAN REVIEW ON UNCERTAINTY</span></div></div></section><section className={styles.manifesto}><div className={styles.manifestoNumber}>THE BOUNDARY</div><p className={styles.manifestoCopy}>The model proposes.<br /><em>Policy gates decide.</em><br />The verifier proves.</p></section><section className={styles.section}><div className={styles.sectionHead}><div><span className={styles.sectionTag}>SAFETY CONTRACT</span></div><div><h2 className={styles.sectionTitle}>A smaller surface<br /><em>earns more trust.</em></h2><p className={styles.sectionLead}>The MVP is deliberately synthetic and bounded. It is designed to be mapped onto the organiser’s sandbox once the target schema and permitted tools are confirmed.</p><div className={styles.submissionItems}><div className={styles.submissionItem}><LockKeyhole size={15} /> Synthetic data and canary identifiers only.</div><div className={styles.submissionItem}><ShieldCheck size={15} /> Human review required for uncertainty.</div><div className={styles.submissionItem}><Check size={15} /> Patch must preserve authorised behaviour.</div><div className={styles.submissionItem}><Code2 size={15} /> Evidence bundle records every decision.</div></div><div className={styles.actionRow}><Link className={styles.accentButton} href="/kavach">See it run <ArrowRight size={14} /></Link><Link className={styles.outlineButton} href="/submission">Read judge brief <ArrowRight size={14} /></Link></div></div></div></section></div></KavachSiteShell>;
}
