import Link from "next/link";
import { ArrowRight, Check, ChevronRight, ShieldCheck, X } from "lucide-react";

import { KavachSiteShell } from "@/components/kavach-site-shell";
import styles from "@/components/kavach-story-pages.module.css";

const cases = [
  { id: "BFLA-001", name: "Administrative delete exposed to operator role", className: "Broken Function Level Authorization", route: "DELETE /api/users/{user_id}", before: "operator_a → DELETE /api/users/operator_b → 204 No Content", after: "operator_a → DELETE /api/users/operator_b → 403 Forbidden", patch: "Require role == admin before invoking the delete handler.", proof: "Operator blocked; admin access preserved; regression suite passed.", severity: "CRITICAL" },
  { id: "BOLA-001", name: "Cross-owner task disclosure", className: "Broken Object Level Authorization", route: "GET /api/tasks/{task_id}", before: "operator_b → GET /api/tasks/task_a → 200 + owner=operator_a", after: "operator_b → GET /api/tasks/task_a → 403 Forbidden", patch: "Enforce object ownership or administrator role before returning the object.", proof: "Non-owner blocked; owner and admin access preserved; tests passed.", severity: "HIGH" },
  { id: "MISCONFIG-001", name: "Debug endpoint enabled in production profile", className: "Security Misconfiguration", route: "GET /api/debug", before: "operator_a → GET /api/debug → 200 { debug: true }", after: "operator_a → GET /api/debug → 404 Not Found", patch: "Disable the debug route in the production configuration.", proof: "Debug exposure removed; normal API access preserved; tests passed.", severity: "MEDIUM" },
];

export default function EvidencePage() {
  const item = cases[0];
  return <KavachSiteShell chapter="02 / THE CASE FILE"><div className={styles.page}><section className={styles.section}><div className={styles.sectionHead}><div><span className={styles.sectionTag}>CASE FILE / {item.id}</span><div className={styles.heroMeta}><i /> VERIFIED IN SYNTHETIC LAB</div></div><div><h1 className={styles.sectionTitle}>The exploit is only<br /><em>the beginning.</em></h1><p className={styles.sectionLead}>A finding becomes valuable when the system can explain the root cause, apply a minimal change, and prove that legitimate behaviour still works.</p></div></div><div className={styles.caseLayout}><aside className={styles.caseNav}>{cases.map((entry, index) => <Link href={index === 0 ? "/evidence" : "/evidence"} className={`${styles.caseNavItem} ${index === 0 ? styles.caseNavSelected : ""}`} key={entry.id}><span><b>{String(index + 1).padStart(2, "0")}</b> {entry.id}</span><ChevronRight size={14} /></Link>)}</aside><article className={styles.casePanel}><div className={styles.casePanelTop}><div><span className={styles.caseLabel}>{item.className}</span><h2>{item.name}</h2></div><span className={styles.casePanelMeta}>{item.severity} / 0.99 CONFIDENCE</span></div><p className={styles.caseSummary}>A regular operator received a successful response from an administrative delete function. The system connected runtime evidence to the route policy and returned a constrained patch strategy.</p><div className={styles.caseEvidence}><div className={styles.caseEvidenceCard}><span className={styles.caseLabel}><X size={13} /> BASELINE EXPLOIT</span><p>{item.before}</p></div><div className={`${styles.caseEvidenceCard} ${styles.caseEvidenceAfter}`}><span className={styles.caseLabel}><Check size={13} /> POST-PATCH PROOF</span><p>{item.after}</p></div></div><div className={styles.patchCallout}><ShieldCheck size={18} /><span><span className={styles.caseLabel}>APPROVED PATCH STRATEGY</span><br />{item.patch}</span></div><div className={styles.stats}><div className={styles.stat}><span>DECISION</span><strong>ACCEPTED</strong><small>policy gate passed</small></div><div className={styles.stat}><span>CONFIDENCE</span><strong>99%</strong><small>source + runtime evidence</small></div><div className={styles.stat}><span>REGRESSION</span><strong>PASS</strong><small>legitimate access preserved</small></div><div className={styles.stat}><span>PROOF</span><strong>LOCKED</strong><small>{item.proof}</small></div></div></article></div></section><section className={styles.manifesto}><div className={styles.manifestoNumber}>THE RULE</div><p className={styles.manifestoCopy}>A patch is not a result until the <em>exploit is blocked</em> and the authorised path survives.</p></section><div className={styles.actionRow}><Link className={styles.accentButton} href="/kavach">Run the control loop <ArrowRight size={14} /></Link><Link className={styles.outlineButton} href="/architecture">Inspect the boundary <ArrowRight size={14} /></Link></div></div></KavachSiteShell>;
}
