import Link from "next/link";
import { ArrowRight, Check, ExternalLink, FileText, Play, ShieldCheck } from "lucide-react";

import { KavachSiteShell } from "@/components/kavach-site-shell";
import styles from "@/components/kavach-story-pages.module.css";

const slides = [
  ["01", "The gap", "Security automation can find a flaw without proving the fix. Kavach makes proof the product."],
  ["02", "The method", "Discover, reason, patch, and prove—one bounded loop with evidence at every hand-off."],
  ["03", "The architecture", "Static and dynamic signals meet structured reasoning inside an isolated worktree."],
  ["04", "The difference", "A safe-stop policy and regression gate turn autonomous suggestion into an auditable decision."],
  ["05", "The delivery", "A working prototype, an evidence bundle, and measurable hooks for the organiser’s finale environment."],
];

export default function SubmissionPage() {
  return <KavachSiteShell chapter="04 / THE JUDGE BRIEF"><div className={styles.page}><section className={styles.section}><div className={styles.sectionHead}><div><span className={styles.sectionTag}>SUBMISSION / FIVE SLIDES</span><div className={styles.heroMeta}><i /> THE STORY IN ONE LINE: FIND → FIX → PROVE</div></div><div><h1 className={styles.sectionTitle}>Make the proof<br /><em>legible.</em></h1><p className={styles.sectionLead}>The proposal is designed as a short visual argument. Each slide answers one judge question and hands the viewer to the next.</p></div></div><div className={styles.submissionLayout}><aside><div className={styles.metaLabel}>JUDGE QUESTION</div><p className={styles.sectionLead}>Can this team build a lightweight system that finds a vulnerability, proposes a safe fix, and proves it holds?</p><div className={styles.quote}>“Not a chatbot. A <em>policy-gated proof loop.</em>”</div></aside><div className={styles.submissionCard}><div className={styles.submissionIndex}>THE FIVE-MOMENT STORY</div><h2>Every slide earns<br />the next one.</h2><div className={styles.submissionItems}>{slides.map(([index, title, copy]) => <div className={styles.submissionItem} key={index}><span className={styles.submissionIndex}>{index}</span><span><strong>{title}</strong><br />{copy}</span></div>)}</div><div className={styles.actionRow}><Link className={styles.accentButton} href="/kavach"><Play size={14} /> Run live demo <ArrowRight size={14} /></Link><Link className={styles.outlineButton} href="/architecture"><FileText size={14} /> Inspect system map</Link></div></div></div></section><section className={styles.section}><div className={styles.sectionHead}><div><span className={styles.sectionTag}>READINESS / CURRENT STATE</span></div><div><h2 className={styles.sectionTitle}>Strong demo.<br /><em>Honest boundary.</em></h2><p className={styles.sectionLead}>The deployed application is a working synthetic MVP. The organiser adapter, hidden holdout, and finale environment are the remaining validation steps.</p><div className={styles.submissionItems}><div className={styles.submissionItem}><Check size={15} /> Live Vercel route verified.</div><div className={styles.submissionItem}><Check size={15} /> 56 repository tests passing.</div><div className={styles.submissionItem}><Check size={15} /> Production build verified.</div><div className={styles.submissionItem}><ShieldCheck size={15} /> No real systems or personal data queried.</div></div><div className={styles.actionRow}><a className={styles.accentButton} href="https://kavach-sentinel.vercel.app/kavach" target="_blank" rel="noreferrer">Open production <ExternalLink size={14} /></a><Link className={styles.outlineButton} href="/evidence">Open case file</Link></div></div></div></section></div></KavachSiteShell>;
}
